version: "3.3"
services:
    discord-bot:
        image: mentoskapraha/big-chungus-bot:v150-pre
        volumes:
            - ./logs:/big-chungus/logs
        environment:
            - DISCORD_BOT_TOKEN=[YOUR_TOKEN_HERE]
            - DB_URI=mongodb://root:AeroStinks@database:27017
            - DB_NAME=prod
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 10
                window: 60s
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
                reservations:
                    cpus: "0.5"
                    memory: 128M

    database:
        image: mongo:6.0.4
        restart: on-failure
        ports:
            - 27017:27017
        volumes:
            - ./mongoDB:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: AeroStinks
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 10
                window: 120s
            resources:
                limits:
                    cpus: "0.5"
                    memory: 512M
                reservations:
                    cpus: "0.25"
                    memory: 128M
